Filters
Aeronnax/pc_market pull request #11
Opened 2024-11-28 17:16 UTC by Aeronnax

2024-11-28 17:21 UTC, Aeronnax commented
Данный PR рассматриваем в контексте Фильтров и их реализации.

2024-11-29 09:20 UTC, 0ldCold requested changes

2024-11-29 09:20 UTC, 0ldCold commented on packages/frontend/src/shared/helpers/addTimeout.ts
> +): Promise<TData> => {
Можно попробовать улучшить
Тут в качестве return типа указать дженерик TPromise

Тогда в теле функции надо написать .catch(error => reject(error))

Возможно тс не будет ругаться

2024-11-29 09:20 UTC, 0ldCold commented on packages/frontend/src/shared/store/cart/cartStore.ts
> -  // TODO: Добавить возможность добавления нескольких элементов (опционально)
Возможно надо вернуть ТУДУ

2024-11-29 09:20 UTC, 0ldCold commented on packages/frontend/src/widgets/market/ProductItemModule/ProductItemModule.tsx
> -// TODO: Переименовать в  ProductItemsModule
Возможно надо вернуть ТУДУ

2024-11-29 10:43 UTC, 0ldCold commented on packages/frontend/src/features/market/PriceFilter/PriceFilter.tsx
> +  };
Мне не очень нравится такое, по сути, дублирование кода
Может как-то объединить их?
Может даже с каррированием?

Типо использование будет выглядеть вот так:

```jsx
<input
  type="number"
  value={minPrice ?? ''}
  onChange={handleMinChange("min")}
  placeholder="Минимальная цена"
/>
```

2024-11-29 10:51 UTC, 0ldCold commented on packages/frontend/src/shared/store/cart/cartStore.ts
> +          const existingProduct = state.cart.find(
find => some

Или как-то использовать результат `find` на 50-й строке
Возможно нужно тогда заменить `find` на `findIndex`
Потом сделать `state.cart[findedIndex].quantity++` и `setCart(state.cart)`

Только не забудь, что если элемент не найден, то у тебя findIndex возвращает -1

2024-12-07 14:02 UTC, 0ldCold requested changes

2024-12-07 14:02 UTC, 0ldCold commented on packages/frontend/src/shared/helpers/addTimeout.ts
> +      });
По моему смысл функции поменялся тут
Она правильно работает?

2024-12-07 14:02 UTC, 0ldCold commented on packages/frontend/src/shared/helpers/addTimeout.ts
> +  }) as TPromise;
Ну через as делать - не выход
Возможно тогда лучше вернуть как было?

2024-12-07 14:03 UTC, 0ldCold commented on packages/frontend/src/widgets/market/ProductItemModule/ProductItemModule.tsx
> -// TODO: Переименовать в  ProductItemsModule
А это?

2024-12-07 14:11 UTC, Aeronnax commented on packages/frontend/src/widgets/market/ProductItemModule/ProductItemModule.tsx
> -// TODO: Переименовать в  ProductItemsModule
Не совсем понимаю. Он и так переименован.

2024-12-07 14:33 UTC, Aeronnax commented on packages/frontend/src/shared/helpers/addTimeout.ts
> +): Promise<TData> => {
Подкорректировал. Да он отрабатывал не корректно.

2024-12-07 14:33 UTC, Aeronnax commented on packages/frontend/src/shared/helpers/addTimeout.ts
> +      });
Подкорректировал. Да он отрабатывал не корректно.

2024-12-07 14:35 UTC, 0ldCold commented on packages/frontend/src/widgets/market/ProductItemModule/ProductItemModule.tsx
> -// TODO: Переименовать в  ProductItemsModule
ProductItem**S**Module

2024-12-07 14:38 UTC, 0ldCold requested changes

2024-12-07 14:38 UTC, 0ldCold commented on packages/frontend/src/shared/helpers/addTimeout.ts
> +  ]);
А это зачем?
Какой смысл в race и в 2-м промисе?

Мне кажется, что проще вернуть как было изначально и оставить как есть

2024-12-07 14:49 UTC, 0ldCold approved these changes

2024-12-07 14:49 UTC, merged